In [20]:
import pandas as pd

In [21]:
dataF = pd.read_csv("wine.csv")

In [22]:
dataF

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,bad
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,good
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,bad
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,good
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,good
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,bad
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,good

In [23]:
dataF.shape

(1599, 12)

In [24]:
dataF.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [25]:
dataF=dataF[dataF["citric acid"]!=0]
dataF

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,bad
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,good
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4,bad
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,good
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.99780,3.35,0.80,10.5,bad
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,bad
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,good
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,good
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,bad
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,good

In [26]:
dataF1 = dataF.drop(["quality"], axis = 1)

In [27]:
dataF1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.99640,3.30,0.46,9.4
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.99780,3.35,0.80,10.5
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [28]:
dataF1.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [29]:
dataF["quality"]=dataF["quality"].map({"bad":0,"good":1})
print(dataF["quality"])

2       0
3       1
6       0
8       1
9       0
       ..
1594    0
1595    1
1596    1
1597    0
1598    1
Name: quality, Length: 1467, dtype: int64

C:\Users\User\AppData\Local\Temp/ipykernel_27260/2319630596.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataF["quality"]=dataF["quality"].map({"bad":0,"good":1})

In [30]:
dataF.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000,1467.000000
mean,8.438582,0.513033,0.295358,2.565815,0.087835,15.926380,47.768916,0.996821,3.298057,0.662965,10.412986,0.540559
std,1.748852,0.171945,0.184819,1.449658,0.048318,10.438805,33.585820,0.001867,0.148996,0.172575,1.053297,0.498522
min,4.600000,0.120000,0.010000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,0.000000
25%,7.200000,0.380000,0.140000,1.900000,0.071000,7.000000,23.000000,0.995700,3.200000,0.550000,9.500000,0.000000
50%,8.000000,0.500000,0.280000,2.200000,0.079000,14.000000,39.000000,0.996800,3.300000,0.620000,10.200000,1.000000
75%,9.400000,0.620000,0.440000,2.600000,0.090000,22.000000,65.000000,0.997900,3.390000,0.740000,11.100000,1.000000
max,15.900000,1.240000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,3.900000,2.000000,14.900000,1.000000

In [32]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

X = dataF.iloc[:, :-1]
y = dataF.iloc[:, -1]

scaler = MinMaxScaler()

scaler.fit(X)

X_scaled = scaler.transform(X)

X_scaled

array([[0.28318584, 0.57142857, 0.03030303, ..., 0.44827586, 0.19161677,
        0.21538462],
       [0.5840708 , 0.14285714, 0.55555556, ..., 0.36206897, 0.1497006 ,
        0.21538462],
       [0.2920354 , 0.42857143, 0.05050505, ..., 0.48275862, 0.07784431,
        0.15384615],
       ...,
       [0.15044248, 0.34821429, 0.12121212, ..., 0.5862069 , 0.25149701,
        0.4       ],
       [0.11504425, 0.46875   , 0.11111111, ..., 0.71551724, 0.22754491,
        0.27692308],
       [0.12389381, 0.16964286, 0.46464646, ..., 0.56034483, 0.19760479,
        0.4       ]])

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(dataF[list(dataF1.columns)],
                                                    dataF["quality"],test_size=0.25,
                                                    random_state=0)

In [39]:
print("Y_train:",Y_train.shape)
print("X_train:",X_train.shape)
X_test
Y_test

Y_train: (1100,)
X_train: (1100, 11)

395     1
1047    0
1052    0
1120    1
840     1
       ..
889     0
1598    1
1515    1
1521    0
867     1
Name: quality, Length: 367, dtype: int64

In [42]:
X_test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
395,12.0,0.370,0.76,4.20,0.066,7.0,38.0,1.00040,3.22,0.60,13.00
1047,7.1,0.430,0.17,1.80,0.082,27.0,51.0,0.99634,3.49,0.64,10.40
1052,5.6,0.605,0.05,2.40,0.073,19.0,25.0,0.99258,3.56,0.55,12.90
1120,7.9,0.540,0.34,2.50,0.076,8.0,17.0,0.99235,3.20,0.72,13.10
840,11.1,0.420,0.47,2.65,0.085,9.0,34.0,0.99736,3.24,0.77,12.10
...,...,...,...,...,...,...,...,...,...,...,...
889,10.7,0.900,0.34,6.60,0.112,23.0,99.0,1.00289,3.22,0.68,9.30
1598,6.0,0.310,0.47,3.60,0.067,18.0,42.0,0.99549,3.39,0.66,11.00
1515,6.9,0.840,0.21,4.10,0.074,16.0,65.0,0.99842,3.53,0.72,9.25
1521,6.9,0.480,0.20,1.90,0.082,9.0,23.0,0.99585,3.39,0.43,9.05
867,6.9,0.510,0.23,2.00,0.072,13.0,22.0,0.99438,3.40,0.84,11.20

In [43]:
Y_test

395     1
1047    0
1052    0
1120    1
840     1
       ..
889     0
1598    1
1515    1
1521    0
867     1
Name: quality, Length: 367, dtype: int64

In [47]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler()